# Generated by Django 4.0.2 on 2022-03-08 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Downtime',
            fields=[
                ('DAID', models.AutoField(primary_key=True, serialize=False)),
                ('DDate', models.DateField()),
                ('LBId', models.IntegerField(null=True)),
                ('Shift', models.CharField(default=None, max_length=2)),
                ('HeadNo', models.IntegerField(null=True)),
                ('DTCode', models.CharField(max_length=10)),
                ('StartTime', models.TimeField()),
                ('EndTime', models.TimeField()),
                ('Status', models.CharField(default=None, max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='LeanBand',
            fields=[
                ('BandId', models.AutoField(primary_key=True, serialize=False)),
                ('TLID', models.CharField(max_length=10)),
                ('GLID', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='ModuleTarget',
            fields=[
                ('MAID', models.AutoField(primary_key=True, serialize=False)),
                ('TDate', models.DateField()),
                ('LBId', models.IntegerField(null=True)),
                ('Shift', models.CharField(default=None, max_length=2)),
                ('HeadNo', models.IntegerField(null=True)),
                ('Style', models.CharField(max_length=15)),
                ('Size', models.CharField(max_length=15)),
                ('planhour', models.IntegerField()),
                ('potenetialhour', models.CharField(max_length=15)),
                ('hour1', models.IntegerField(null=True)),
                ('hour2', models.IntegerField(null=True)),
                ('hour3', models.IntegerField(null=True)),
                ('hour4', models.IntegerField(null=True)),
                ('hour5', models.IntegerField(null=True)),
                ('hour6', models.IntegerField(null=True)),
                ('hour7', models.IntegerField(null=True)),
                ('hour8', models.IntegerField(null=True)),
                ('hour9', models.IntegerField(null=True)),
                ('hour10', models.IntegerField(null=True)),
                ('hour11', models.IntegerField(null=True)),
                ('hour12', models.IntegerField(null=True)),
            ],
        ),
    ]
