# Generated by Django 4.0.2 on 2022-03-20 06:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('targetboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DowntimeCode',
            fields=[
                ('_id', models.AutoField(primary_key=True, serialize=False)),
                ('DTCode', models.CharField(max_length=10)),
                ('Department', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='HeadDowntime',
            fields=[
                ('_id', models.AutoField(primary_key=True, serialize=False)),
                ('StartTime', models.TimeField()),
                ('EndTime', models.TimeField()),
                ('Status', models.CharField(default=None, max_length=10)),
                ('DTCode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='targetboard.downtimecode')),
            ],
        ),
        migrations.CreateModel(
            name='HeadsTarget',
            fields=[
                ('_Id', models.AutoField(primary_key=True, serialize=False)),
                ('HeadNumber', models.IntegerField(null=True)),
                ('Style', models.CharField(max_length=15)),
                ('Size', models.CharField(max_length=15)),
                ('planhour', models.IntegerField()),
                ('potenetialhour', models.CharField(max_length=15)),
                ('hour1', models.IntegerField(null=True)),
                ('hour2', models.IntegerField(null=True)),
                ('hour3', models.IntegerField(null=True)),
                ('hour4', models.IntegerField(null=True)),
                ('hour5', models.IntegerField(null=True)),
                ('hour6', models.IntegerField(null=True)),
                ('hour7', models.IntegerField(null=True)),
                ('hour8', models.IntegerField(null=True)),
                ('hour9', models.IntegerField(null=True)),
                ('hour10', models.IntegerField(null=True)),
                ('hour11', models.IntegerField(null=True)),
                ('hour12', models.IntegerField(null=True)),
                ('hour1re', models.IntegerField(null=True)),
                ('hour2re', models.IntegerField(null=True)),
                ('hour3re', models.IntegerField(null=True)),
                ('hour4re', models.IntegerField(null=True)),
                ('hour5re', models.IntegerField(null=True)),
                ('hour6re', models.IntegerField(null=True)),
                ('hour7re', models.IntegerField(null=True)),
                ('hour8re', models.IntegerField(null=True)),
                ('hour9re', models.IntegerField(null=True)),
                ('hour10re', models.IntegerField(null=True)),
                ('hour11re', models.IntegerField(null=True)),
                ('hour12re', models.IntegerField(null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Downtime',
        ),
        migrations.RenameField(
            model_name='leanband',
            old_name='BandId',
            new_name='_Id',
        ),
        migrations.RenameField(
            model_name='moduletarget',
            old_name='planhour',
            new_name='HeadCount',
        ),
        migrations.RenameField(
            model_name='moduletarget',
            old_name='MAID',
            new_name='_Id',
        ),
        migrations.RemoveField(
            model_name='leanband',
            name='GLID',
        ),
        migrations.RemoveField(
            model_name='leanband',
            name='TLID',
        ),
        migrations.RemoveField(
            model_name='moduletarget',
            name='HeadNo',
        ),
        migrations.RemoveField(
            model_name='moduletarget',
            name='LBId',
        ),
        migrations.RemoveField(
            model_name='moduletarget',
            name='Size',
        ),
        migrations.RemoveField(
            model_name='moduletarget',
            name='Style',
        ),
        migrations.RemoveField(
            model_name='moduletarget',
            name='hour1',
        ),
        migrations.RemoveField(
            model_name='moduletarget',
            name='hour10',
        ),
        migrations.RemoveField(
            model_name='moduletarget',
            name='hour11',
        ),
        migrations.RemoveField(
            model_name='moduletarget',
            name='hour12',
        ),
        migrations.RemoveField(
            model_name='moduletarget',
            name='hour2',
        ),
        migrations.RemoveField(
            model_name='moduletarget',
            name='hour3',
        ),
        migrations.RemoveField(
            model_name='moduletarget',
            name='hour4',
        ),
        migrations.RemoveField(
            model_name='moduletarget',
            name='hour5',
        ),
        migrations.RemoveField(
            model_name='moduletarget',
            name='hour6',
        ),
        migrations.RemoveField(
            model_name='moduletarget',
            name='hour7',
        ),
        migrations.RemoveField(
            model_name='moduletarget',
            name='hour8',
        ),
        migrations.RemoveField(
            model_name='moduletarget',
            name='hour9',
        ),
        migrations.RemoveField(
            model_name='moduletarget',
            name='potenetialhour',
        ),
        migrations.AddField(
            model_name='leanband',
            name='lbname',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='moduletarget',
            name='lb_Id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='targetboard.leanband'),
        ),
        migrations.AlterField(
            model_name='moduletarget',
            name='Shift',
            field=models.CharField(max_length=2),
        ),
        migrations.AddField(
            model_name='headstarget',
            name='module_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='targetboard.moduletarget'),
        ),
        migrations.AddField(
            model_name='headdowntime',
            name='Head_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='targetboard.headstarget'),
        ),
    ]
