# Generated by Django 4.0.2 on 2022-03-08 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('targetboard', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='moduletarget',
            old_name='planhour',
            new_name='PlanH',
        ),
        migrations.RenameField(
            model_name='moduletarget',
            old_name='potenetialhour',
            new_name='PotentialH',
        ),
        migrations.AlterField(
            model_name='moduletarget',
            name='hour1',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='moduletarget',
            name='hour10',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='moduletarget',
            name='hour11',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='moduletarget',
            name='hour12',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='moduletarget',
            name='hour2',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='moduletarget',
            name='hour3',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='moduletarget',
            name='hour4',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='moduletarget',
            name='hour5',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='moduletarget',
            name='hour6',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='moduletarget',
            name='hour7',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='moduletarget',
            name='hour8',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='moduletarget',
            name='hour9',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
